name: Lint and Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Chrome
      run: |
        LATEST_CHROME=$(curl -sS https://dl.google.com/linux/chrome/deb/dists/stable/main/binary-amd64/Packages | grep -oP "(?<=^Filename: ).*" | grep 'google-chrome-stable.*amd64.deb' | head -n1)
        wget "https://dl.google.com/linux/chrome/deb/$LATEST_CHROME"
        sudo apt-get update
        sudo apt-get install ./$(basename "$LATEST_CHROME")

    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@v2
      with:
       chromedriver-version: '88.0.4324.96'
    - run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Lint Code Base
      uses: github/super-linter@v5
      env:
        VALIDATE_ALL_CODEBASE: true
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build with Maven
      run: mvn package --file pom.xml
      
    - name: Run tests
      run: mvn -B test
